### ISSUE TITLE
Could you please add these video courses to your list

### ISSUE THREAD

**Issue by jayakumark** [handong1587/handong1587.github.io#1]
https://www.reddit.com/r/MachineLearning/comments/51qhc8/phdlevel_courses/

**Comment by handong1587** [comment]
Thanks for sharing!
Now I have added these courses to my blog page: 
https://handong1587.github.io/machine_learning/2015/08/27/ml-courses.html#phd-level-courses-with-video-lectures
https://github.com/handong1587/handong1587.github.io/blob/master/_posts/machine_learning/2015-08-27-ml-courses.md#phd-level-courses-with-video-lectures
