### ISSUE TITLE
Add Github page for CliqueCNN

### ISSUE THREAD

**Issue by asanakoy** [handong1587/handong1587.github.io#2]
Hi,   
could you please add a link to our project page for "**CliqueCNN:Deep Unsupervised Exemplar Learning**" in `dl-resources.html`
https://github.com/asanakoy/cliquecnn

**Comment by handong1587** [comment]
Hi, I add the project page link. Thanks for your sharing!

**Comment by handong1587** [comment]
Hi, I add your project page link to this blog.
Thanks for your sharing!
